/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lessons with optional filters and pagination
         * @description Returns lessons sorted by volume ASC, lesson_number ASC.
         *     Supports filtering by volume, kitab, bab, and text search on title_ar.
         *     Cached at CDN edge for 60 seconds.
         */
        get: operations["listLessons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single lesson by ID */
        get: operations["getLessonById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate as admin — returns session cookie
         * @description Validates admin password. On success, sets HttpOnly iron-session cookie.
         *     Rate limited to 5 requests per 15 minutes per IP.
         *     Wrong password always returns 401 with generic message (no enumeration).
         */
        post: operations["adminAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new lesson record */
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update lesson metadata (partial update — only provided fields change)
         * @description id, volume, and lesson_number are immutable and cannot be updated.
         *     Provide only the fields that should change.
         */
        put: operations["updateLesson"];
        post?: never;
        /**
         * Permanently delete a lesson
         * @description Hard delete. Removes lesson from lessons.json. Cannot be undone via API — only via GitHub history revert.
         */
        delete: operations["deleteLesson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload audio file to Internet Archive via backend proxy
         * @description Accepts multipart/form-data. Streams file to Internet Archive S3.
         *     Returns the archive_url to use when creating the lesson record.
         *     Filename generated as: lesson-v{volume}-{lesson_number_padded3}.mp3
         *     Max file size: 500MB.
         */
        post: operations["uploadAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Chapter: {
            /** @example كتاب الطهارة */
            kitab: string;
            /** @example باب الماء */
            bab: string | null;
            /** @example null */
            fasl: string | null;
        };
        Lesson: {
            /** @example 1 */
            readonly id: number;
            /**
             * @example 1
             * @enum {integer}
             */
            volume: 1 | 2 | 3 | 4;
            /** @example 1 */
            lesson_number: number;
            /** @example قول المصنف: باب في أحكام الطهارة */
            title_ar: string;
            chapter: components["schemas"]["Chapter"];
            /** @example 3720 */
            duration_seconds: number;
            /**
             * Format: date
             * @example 2023-01-15
             */
            upload_date: string;
            /**
             * Format: uri
             * @example https://archive.org/download/tuhfat-al-muhtaj-abdulhakim-saadi/lesson-v1-001.mp3
             */
            archive_url: string;
            /** @example 12 */
            telegram_post_id: number;
        };
        LessonCreateBody: {
            /**
             * @example 1
             * @enum {integer}
             */
            volume: 1 | 2 | 3 | 4;
            /** @example 214 */
            lesson_number: number;
            /** @example قول المصنف: فصل في أحكام الغسل */
            title_ar: string;
            chapter: components["schemas"]["Chapter"];
            /** @example 4200 */
            duration_seconds: number;
            /**
             * Format: date
             * @example 2026-04-01
             */
            upload_date: string;
            /**
             * Format: uri
             * @example https://archive.org/download/tuhfat-al-muhtaj-abdulhakim-saadi/lesson-v1-214.mp3
             */
            archive_url: string;
            /** @example 679 */
            telegram_post_id: number;
        };
        LessonUpdateBody: {
            /** @example قول المصنف: فصل في أحكام الغسل — مراجعة */
            title_ar?: string;
            chapter?: components["schemas"]["Chapter"];
            /** @example 4350 */
            duration_seconds?: number;
            /**
             * Format: date
             * @example 2026-04-01
             */
            upload_date?: string;
            /**
             * Format: uri
             * @example https://archive.org/download/tuhfat-al-muhtaj-abdulhakim-saadi/lesson-v1-214.mp3
             */
            archive_url?: string;
            /** @example 679 */
            telegram_post_id?: number;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            requestId: string;
            /**
             * Format: date-time
             * @example 2026-04-20T10:00:00.000Z
             */
            timestamp: string;
            /**
             * @description Total count (only present on list endpoints)
             * @example 648
             */
            total?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        ApiError: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Request validation failed */
                message: string;
                /**
                 * @example {
                 *       "lesson_number": "Must be a positive integer"
                 *     }
                 */
                details?: {
                    [key: string]: unknown;
                };
            };
            /**
             * Format: uuid
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            requestId: string;
            /**
             * Format: date-time
             * @example 2026-04-20T10:00:00.000Z
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description Session cookie missing, invalid, or expired */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Authentication required",
                 *         "details": {}
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Lesson not found",
                 *         "details": {}
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Zod validation failure — field-level errors in details */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Request validation failed",
                 *         "details": {
                 *           "title_ar": "Required",
                 *           "volume": "Must be one of: 1, 2, 3, 4"
                 *         }
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Duplicate lesson_number in volume OR GitHub SHA conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "DUPLICATE_LESSON_NUMBER",
                 *         "message": "A lesson with this number already exists in volume 1",
                 *         "details": {}
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until the rate limit window resets */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "Too many requests. Please try again later.",
                 *         "details": {
                 *           "retryAfterSeconds": 60
                 *         }
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unexpected server error (no stack trace) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INTERNAL_ERROR",
                 *         "message": "An unexpected error occurred",
                 *         "details": {}
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description GitHub API or Internet Archive unreachable */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UPSTREAM_ERROR",
                 *         "message": "External service unavailable. Please try again.",
                 *         "details": {}
                 *       },
                 *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                 *       "timestamp": "2026-04-20T10:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLessons: {
        parameters: {
            query?: {
                /**
                 * @description Filter by volume number
                 * @example 1
                 */
                volume?: 1 | 2 | 3 | 4;
                /**
                 * @description Exact match on chapter.kitab
                 * @example كتاب الطهارة
                 */
                kitab?: string;
                /**
                 * @description Exact match on chapter.bab
                 * @example باب الماء
                 */
                bab?: string;
                /**
                 * @description Substring match on title_ar
                 * @example الطهارة
                 */
                search?: string;
                /** @example 50 */
                limit?: number;
                /** @example 0 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lessons retrieved successfully */
            200: {
                headers: {
                    /** @example public, s-maxage=60, stale-while-revalidate=300 */
                    "Cache-Control"?: string;
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            lessons: components["schemas"]["Lesson"][];
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            /** @description Invalid query parameter type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getLessonById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            lesson: components["schemas"]["Lesson"];
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            /** @description ID is not a valid integer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    adminAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example your_admin_password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authentication successful. Session cookie set. */
            200: {
                headers: {
                    /** @example tuhfa_session=<token>; HttpOnly; Secure; SameSite=Strict; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @example true */
                            authenticated: boolean;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            /** @description Invalid password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_CREDENTIALS",
                     *         "message": "Invalid credentials",
                     *         "details": {}
                     *       },
                     *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                     *       "timestamp": "2026-04-20T10:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreateBody"];
            };
        };
        responses: {
            /** @description Lesson created and committed to GitHub */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            lesson: components["schemas"]["Lesson"];
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    updateLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 649 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdateBody"];
            };
        };
        responses: {
            /** @description Lesson updated and committed to GitHub */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            lesson: components["schemas"]["Lesson"];
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            /** @description ID is not a valid integer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 649 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ID is not a valid integer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    uploadAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Audio file. Max 500MB. Accepted types — audio/mpeg, audio/mp4, audio/ogg, audio/wav.
                     */
                    file: string;
                    /**
                     * @example 1
                     * @enum {string}
                     */
                    volume: "1" | "2" | "3" | "4";
                    /** @example 214 */
                    lesson_number: string;
                };
            };
        };
        responses: {
            /** @description File uploaded to Internet Archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /**
                             * Format: uri
                             * @example https://archive.org/download/tuhfat-al-muhtaj-abdulhakim-saadi/lesson-v1-214.mp3
                             */
                            archive_url: string;
                            /** @example lesson-v1-214.mp3 */
                            filename: string;
                            /** @example 104857600 */
                            size_bytes: number;
                        };
                        meta: components["schemas"]["ResponseMeta"];
                    };
                };
            };
            /** @description Missing file or invalid form fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description File exceeds 500MB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "FILE_TOO_LARGE",
                     *         "message": "File exceeds maximum size of 500MB",
                     *         "details": {}
                     *       },
                     *       "requestId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                     *       "timestamp": "2026-04-20T10:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamError"];
        };
    };
}
